### ISSUE TITLE
Add the ability to create child logger

### ISSUE THREAD

**Issue by yovanoc** [theogravity/loglayer#8]

**Comment by theogravity** [comment]
What's the use-case for this? Having no description doesn't help.

**Comment by yovanoc** [comment]
Hi, I use Pino, and I think it would be cool to use this through loglayer: https://github.com/pinojs/pino/blob/master/docs/child-loggers.md

I have to recreate a complete logger every time but only needed some context for each. Child logger is the perfect use for this and I can't through loglayer. Thanks

**Comment by theogravity** [comment]
So basically child would copy the existing context and that's it? Not a problem to do.

**Comment by yovanoc** [comment]
It's not only context, it copies everything I guess, all the options like streams etc but with the ability to add more default context

**Comment by theogravity** [comment]
> It's not only context, it copies everything I guess, all the options like streams etc but with the ability to add more default context

You basically want the instance options you used to create `LogLayer` + context

**Comment by yovanoc** [comment]
Yes just the child method of pino i guess

**Comment by theogravity** [comment]
Should be published under `1.4.1`

**Comment by yovanoc** [comment]
Perfect, Sad we can't use the real child method but yeah this will do it thanks

**Comment by theogravity** [comment]
Not sure why you would want to since things like context is kept by this lib and not the logger, and not all loggers offer a child method.
